language: node_js
before_install:
- nvm install stable
- npm update
- npm install -g npm
- npm install -g cordova gulp ionic@beta
- node --version
- npm --version
script:
- npm install
- ionic platform add android
- gulp build
